# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 耒耒耒耒耒
subtitle: 张未的技术博客
description: 本站是耒耒耒耒耒（张未）的个人技术博客。内容涵盖微服务架构、DDD、Java后端技术、领域驱动等相关的研究与知识分享。
keywords: 微服务, DDD, Java
author: 张未
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://blog.weechang.xyz
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
tagcloud_dir: tagcloud
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map: Spring Cloud
tag_map: Java,Spring Cloud

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page
archive_generator:
  per_page: 0
tag_generator:
  per_page: 0
category_generator:
  per_page: 0

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: icarus

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
#  type: baidu_url_submitter
  type: git
  branch: master
  repo:
    coding: https://git.coding.net/weechang93/weechang93.coding.me.git
    github: https://github.com/weechang/weechang.github.io.git
  bucket: blog.weechang.xyz

# Search
## hexo-generator-search
search:
  path: search.xml
  field: all

# Extensions
## Plugins: http://hexo.io/plugins/
#RSS订阅
plugin:
- hexo-generator-feed
#Feed Atom
feed:
type: atom
path: atom.xml
limit: 20

#baidu url
baidu_url_submit:
  count: 1
  host: blog.weechang.xyz
  token: 0dIARTecXqio3U5a
  path: baidu_urls.txt

#nofollow not include
nofollow:
  enable: true
  exclude:
  - blog.unknowns.info
  - yanhaijing.com